In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("datasets/diabetes.csv")
df.head()

   gender   age  hypertension  ...  HbA1c_level blood_glucose_level  diabetes
0  Female  80.0             0  ...          6.6                 140         0
1  Female  54.0             0  ...          6.6                  80         0
2    Male  28.0             0  ...          5.7                 158         0
3  Female  36.0             0  ...          5.0                 155         0
4    Male  76.0             1  ...          4.8                 155         0

[5 rows x 9 columns]

In [3]:
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0,'Other':1})

In [4]:
df = pd.get_dummies(
    df,
    columns=['smoking_history'],
    drop_first=True,
    dtype=int
)
df.head()

   gender   age  ...  smoking_history_never  smoking_history_not current
0       0  80.0  ...                      1                            0
1       0  54.0  ...                      0                            0
2       1  28.0  ...                      1                            0
3       0  36.0  ...                      0                            0
4       1  76.0  ...                      0                            0

[5 rows x 13 columns]

In [5]:
num_cols = ['age', 'bmi', 'HbA1c_level', 'blood_glucose_level']
all_cols = df.columns.drop('diabetes')

In [6]:
from xgboost import XGBClassifier
model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    eval_metric='logloss',
    random_state=42
)

In [7]:
X = df.drop('diabetes', axis=1)
y = df['diabetes']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.97225

In [9]:
import pickle
with open('diabetes.pkl', 'wb') as f:
    pickle.dump(model, f)