In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("datasets/lung_txt.csv")
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
0,M,65,1,1,1,2,2,1,2,2,2,2,2,2,1,NO
1,F,55,1,2,2,1,1,2,2,2,1,1,1,2,2,NO
2,F,78,2,2,1,1,1,2,1,2,1,1,2,1,1,YES
3,M,60,2,1,1,1,2,1,2,1,1,2,1,2,2,YES
4,F,80,1,1,2,1,1,2,1,2,1,1,1,1,2,NO

In [3]:
from sklearn.preprocessing import LabelEncoder
columns_to_drop=['ANXIETY','PEER_PRESSURE','CHRONIC_DISEASE','GENDER','AGE','ALCOHOL_CONSUMING']
df=df.drop(columns=columns_to_drop)
label_encoder = LabelEncoder()
df['LUNG_CANCER'] = label_encoder.fit_transform(df['LUNG_CANCER'])
columns_to_transform = ['SMOKING', 'YELLOW_FINGERS', 'FATIGUE', 'ALLERGY', 'WHEEZING', 'COUGHING','SHORTNESS_OF_BREATH','SWALLOWING_DIFFICULTY','CHEST_PAIN']
df[columns_to_transform] = df[columns_to_transform].replace({1: 0, 2: 1})
df.head()

,SMOKING,YELLOW_FINGERS,FATIGUE,ALLERGY,WHEEZING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
0,0,0,0,1,1,1,1,1,0,0
1,0,1,1,1,1,0,0,1,1,0
2,1,1,1,0,1,0,1,0,0,1
3,1,0,0,1,0,1,0,1,1,1
4,0,0,1,0,1,0,0,0,1,0

In [4]:
y = df.iloc[:, 9]
x = df.drop(columns=['LUNG_CANCER'])
feature_column_names = x.columns.tolist()

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
x, y = make_classification(n_samples=500, n_features=5, random_state=42)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
model = KNeighborsClassifier(n_neighbors=10)
model.fit(x_train_scaled, y_train)
from sklearn.metrics import accuracy_score
y_pred = model.predict(x_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
results_df = pd.DataFrame({
    'LUNG_CANCER': y_pred
})
print(results_df)

Accuracy: 94.00%
    LUNG_CANCER
0             0
1             1
2             1
3             1
4             0
..          ...
95            1
96            0
97            0
98            1
99            0

[100 rows x 1 columns]

In [7]:
import joblib
joblib.dump(model, 'lung_txt.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']